import * as THREE from "three";import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader.js";import {invoke} from "@tauri-apps/api/core";import {RenderScheduler} from "./render_scheduler";
export type Scale="small"|"medium"|"large";export type Settings={schemaVersion:number;character:{visible:boolean;scale:Scale;position:{x:number;y:number};alwaysOnTop:boolean;currentId:string};performance:{lowPower:boolean}};type Payload={id:string;data:number[]}|null;
export const sizes:Record<Scale,number>={small:280,medium:360,large:460};
export class CharacterScene{scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(32,1,.01,100);renderer:THREE.WebGLRenderer;scheduler:RenderScheduler;model:THREE.Object3D|null=null;private loader=new GLTFLoader();
constructor(canvas:HTMLCanvasElement,lowPower:boolean){this.renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:!lowPower,powerPreference:lowPower?"low-power":"high-performance"});this.renderer.setPixelRatio(Math.min(devicePixelRatio,lowPower?1:2));this.renderer.setClearColor(0,0);this.scene.add(new THREE.HemisphereLight(0xffffff,0x444450,2.2));const key=new THREE.DirectionalLight(0xffffff,2.5);key.position.set(2,4,5);this.scene.add(key);this.scheduler=new RenderScheduler(()=>this.renderer.render(this.scene,this.camera))}
dispose(){if(this.model)this.disposeObject(this.model);this.renderer.dispose();this.renderer.getContext().getExtension("WEBGL_lose_context")?.loseContext();this.scheduler.dispose()}
private disposeObject(root:THREE.Object3D){root.traverse(n=>{const m=n as THREE.Mesh;if(!m.isMesh)return;m.geometry.dispose();for(const mat of (Array.isArray(m.material)?m.material:[m.material])){for(const v of Object.values(mat))if(v instanceof THREE.Texture)v.dispose();mat.dispose()}})}
private fit(root:THREE.Object3D){const box=new THREE.Box3().setFromObject(root);const size=box.getSize(new THREE.Vector3());root.position.sub(box.getCenter(new THREE.Vector3()));root.scale.setScalar(2.8/Math.max(size.x,size.y,size.z,.001));const b=new THREE.Box3().setFromObject(root);root.position.sub(b.getCenter(new THREE.Vector3()));const s=b.getSize(new THREE.Vector3());this.camera.position.set(0,s.y*.45,Math.max(s.y*1.45,3.4));this.camera.lookAt(0,s.y*.05,0);this.camera.updateProjectionMatrix()}
placeholder(){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.CapsuleGeometry(.72,1.45,8,16),new THREE.MeshStandardMaterial({color:0x4b4b55,roughness:.8})));const h=new THREE.Mesh(new THREE.SphereGeometry(.58,24,16),new THREE.MeshStandardMaterial({color:0x777783,roughness:.75}));h.position.y=1.2;g.add(h);g.userData.placeholder=true;this.scene.add(g);this.model=g;this.fit(g)}
async load(){if(this.model){this.disposeObject(this.model);this.scene.remove(this.model);this.model=null}const p=await invoke<Payload>("get_character_model");if(!p){this.placeholder();this.scheduler.requestRender();return}await new Promise<void>(resolve=>this.loader.parse(new Uint8Array(p.data).buffer,"",g=>{this.model=g.scene;this.scene.add(this.model);this.fit(this.model);this.scheduler.requestRender();resolve()},()=>{this.placeholder();this.scheduler.requestRender();resolve()}))}
rotateOnce(){if(!this.model||this.model.userData.placeholder)return;const start=performance.now(),base=this.model.rotation.y;this.scheduler.setActive(true);const tick=(now:number)=>{if(!this.model)return;const t=Math.min((now-start)/2000,1);this.model.rotation.y=base+Math.PI*2*t;this.scheduler.requestRender();if(t<1)requestAnimationFrame(tick);else this.scheduler.setActive(false)};requestAnimationFrame(tick)}}